# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e788b2c00fba88c614d7cb23834867a313b9b5dba0e5b4748730fc341f229be5b864fd8279884b43af62f6f3b807b6bbbe3d2f47de4bdd5f6c1d0aaac717c3d

test:
  secret_key_base: 542d91ffb11eb0134c0f6a9c7e48274b9f2f50d4ad6ef8a80a5c53765d5776ee01a2ec6cce9c3d0efab2fd95fc43b6bbdc0bd895f36d4062648964c3809a64c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
